# Site settings
title: Shil.ch
email: me@shil.ch
description: Shil's private Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shil.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
